# Auto-generated raw CSS rules from design tokens
# Do not edit directly - regenerate with tools/generate_raw_rules.py

RAW_RULES = {'.tailored-resume-content': {'font-family': "'Calibri', Arial, sans-serif",
                              'font-size': '11pt',
                              'line-height': '1.25',
                              'color': '#333'},
 '.tailored-resume-content p': {'margin-block': '0rem'},
 '.tailored-resume-content ul': {'margin-block': '0rem', 'list-style-type': 'none', 'padding-left': '0'},
 '.tailored-resume-content ol': {'margin-block': '0rem', 'padding-left': '0'},
 '.tailored-resume-content li': {'margin-block': '0rem'},
 '.job-content p, .education-content p, .project-content p': {'margin-block': '0rem'},
 '.job-content ul, .education-content ul, .project-content ul': {'margin-block': '0rem'},
 '.job-content ol, .education-content ol, .project-content ol': {'margin-block': '0rem'},
 '.job-content li, .education-content li, .project-content li': {'margin-block': '0rem'},
 '.role-description-text': {'margin-top': '0rem',
                            'margin-bottom': '0rem',
                            'font-style': 'italic',
                            'color': '#555',
                            'display': 'block',
                            'width': '100%'},
 '.role-box + ul': {'margin-top': '0rem'},
 '.resume-section': {'margin-bottom': '0.8rem'},
 '.section-box': {'margin-bottom': '0.5rem',
                  'border': '2px solid #4a6fdc',
                  'background': 'transparent',
                  'color': '#4a6fdc',
                  'font-weight': '700',
                  'padding': '1px 12px',
                  'font-size': '12pt',
                  'line-height': '1.0'},
 '.position-bar': {'margin-top': '0rem',
                   'margin-bottom': '0rem',
                   'background': '#FFFFFF',
                   'padding': '0.25rem 0.45rem'},
 '.position-line': {'margin-bottom': '0rem'},
 '.job-content': {'margin-top': '0rem'},
 '.education-content': {'margin-top': '0rem'},
 '.project-content': {'margin-top': '0rem'},
 '.bullets li': {'break-inside': 'avoid'},
 '.bullets li::before': {'content': '"\\2022 "', 'color': '#3A3A3A', 'font-weight': 'normal'},
 '.skills-content': {'margin-left': '0'},
 '.skills-content p': {'margin-bottom': '0.15rem'},
 '.skills-content ul': {'list-style-type': 'none', 'padding-left': '0'},
 '.skills-content li': {'margin-bottom': '0rem', 'line-height': '1.25'},
 '.skills-content li::before': {'content': '"\\2022 "', 'color': '#3A3A3A', 'font-weight': 'normal'},
 '.role-box': {'border-color': '#4A6FDC',
               'border-width': '1px',
               'padding': '4px',
               'background-color': '#F8F9FA',
               'color': '#333333',
               'border-radius': '0.5px',
               'display': 'flex',
               'justify-content': 'space-between',
               'align-items': 'center'},
 '.role-box .role': {'font-weight': 'bold', 'flex-grow': '1'},
 '.role-box .dates': {'font-style': 'italic', 'margin-left': '1rem', 'white-space': 'nowrap'},
 '.contact-section': {'text-align': 'center', 'margin-bottom': '1rem'},
 '.contact-section .name': {'font-size': '16pt', 'font-weight': '700', 'color': '#343a40', 'margin-bottom': '0.5rem'},
 '.contact-divider': {'border': 'none',
                      'height': '1px',
                      'background-color': '#343a40',
                      'width': '90%',
                      'margin': '1rem auto'},
 '.summary-content, .experience-content, .education-content, .skills-content, .projects-content': {'margin-left': '0'},
 '.visually-hidden': {'position': 'absolute !important',
                      'width': '1px !important',
                      'height': '1px !important',
                      'padding': '0 !important',
                      'margin': '-1px !important',
                      'overflow': 'hidden !important',
                      'clip': 'rect(0, 0, 0, 0) !important',
                      'white-space': 'nowrap !important',
                      'border': '0 !important'}}
